### ISSUE TITLE
ecs task fails - exec ./watchdog.sh: no such file or directory

### ISSUE THREAD

**Issue by archenovalis** [schuettc/cdk-minecraft#9]
Built and deployed on windows 10 using docker desktop.

everything works up until ecs task fails with watchdog container throwing exit code 1.

ecs task log shows
"exec ./watchdog.sh: no such file or directory"

build/deploy log shows
[3/4] COPY ./watchdog.sh .
DONE 0.1s

[4/4] RUN chmod +x ./watchdog.sh
DONE 0.4s

exporting to image
exporting layers
exporting layers 0.8s done

**Comment by archenovalis** [comment]
also confirmed that running the container locally throws the same error

**Comment by archenovalis** [comment]
resolved the issue caused by windows with the following added to DockerFile to remove window's end of line "\r":
COPY ./watchdog.sh .
**RUN sed -i 's/\r$//' ./watchdog.sh**
RUN chmod +x ./watchdog.sh

New error:
exec ./watchdog.sh: exec format error

**Comment by archenovalis** [comment]
resolved error by changing ecs.ts:
cpuArchitecture: CpuArchitecture.ARM64,
to
cpuArchitecture: CpuArchitecture.X86_64,

**Comment by archenovalis** [comment]
all issues resolved. perhaps add these notes somewhere and maybe add the sed line as a failsafe

**Comment by archenovalis** [comment]
all issues resolved. perhaps add these notes somewhere and maybe add the sed line as a failsafe

**Comment by schuettc** [comment]
It wasn't building correctly for you locally?  Is that what was happening?  Could probably work out a more robust multi-architecture deployment.

**Comment by archenovalis** [comment]
Correct. When compiling on Windows and Intel processor, Windows was adding
\r to each line and compiling it for Intel architecture. Needed to remove
the \r from each line and changed AWS ECS architecture to match.
